@extends('frontend.layouts.app')
@section('title','Home')
@section('content')
    @include('frontend.sections.home.banner')
    @include('frontend.sections.home.fasilitas')
    @include('frontend.sections.home.about')
    @include('frontend.sections.home.layanan')
   {{--
    @include('frontend.sections.home.team')
    @include('frontend.sections.home.berita')
    @include('frontend.sections.home.galleries')
    @include('frontend.sections.home.ikm')
    @include('frontend.sections.home.pengunjung')--}}
@endsection
